language: ruby

rvm:
  - 1.8.7
  - 2.1.8
  - 2.2.4
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.2.3.mysql2
  - gemfiles/Gemfile.3.2.mysql2
  - gemfiles/Gemfile.4.2.mysql2
  - gemfiles/Gemfile.4.2.pg
  - gemfiles/Gemfile.5.0.mysql2
  - gemfiles/Gemfile.5.0.pg
  - gemfiles/Gemfile.5.0.sqlite3

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.2.3.mysql2
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.2.3.mysql2
      rvm: 2.2.4
    - gemfile: gemfiles/Gemfile.2.3.mysql2
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.3.2.mysql2
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.4.2.mysql2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.4.2.pg
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0.mysql2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0.pg
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0.sqlite3
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0.mysql2
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.5.0.pg
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.5.0.sqlite3
      rvm: 2.1.8

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - psql -c 'create database gemika_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS gemika_test;'

script: bundle exec rake current_rspec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de
