language: ruby

rvm:
  - 1.8.7
  - 2.1.8
  - 2.2.4
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.2.3.mysql2
  - gemfiles/Gemfile.3.2.mysql2
  - gemfiles/Gemfile.4.2.mysql2
  - gemfiles/Gemfile.4.2.pg
  - gemfiles/Gemfile.5.0.mysql2
  - gemfiles/Gemfile.5.0.pg

install:
  # Old Travis CI bundler explodes when lockfile version doesn't match recently bumped version
  - gem install bundler --version='=1.12.5'
  # This is the default Travis CI install step
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - psql -c 'create database gemika_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS gemika_test;'

script: bundle exec rake gemika:spec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.4.2.mysql2
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.4.2.pg
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.5.0.mysql2
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.5.0.pg
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.2.3.mysql2
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.5.0.mysql2
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.5.0.pg
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.2.3.mysql2
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.2.3.mysql2
